# Generated by Django 2.2.4 on 2019-08-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipie_box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='recipie_box.Author'),
        ),
    ]
